README.md

docs: add gif in the repo README.md

---

mkdocs.yml

docs: correct link to installation

---

README.md
docs/index.md

docs: simplify plugin first statement

---

docs/index.md

As they are already implemented

docs: remove RSS feeds as future plans

---

.pre-commit-config.yaml
docs/requirements.txt
requirements-dev.txt
requirements.txt

ci: change black pre-commit version to master

---

README.md

The file containing the "Commit message guidelines" section was moved to another path.

fix(README.md): Broken link

---

.github/workflows/install.yml

It was using the command line to get the version, but this library
doesn't have one

ci: fix install pipeline

---

.github/workflows/install.yml

ci: correct the package to install in the install pipeline

---

docs/install.md
pdm.lock
pyproject.toml

mkdocs-material and mkdocs-git-revision-date-localized-plugin m
docs: add a note that the mkdocs.yaml needs to have a nav section

fix: add the missing requirements

---

pyproject.toml

ci: remove deprecation warning for mkdocs-material

---

pdm.lock
pyproject.toml

tests: remove deprecation warning on mkdocs

---

.cruft.json
.github/workflows/build.yml
.github/workflows/tests.yml
.github/workflows/update.yml
.gitignore
Makefile
README.md
docs/index.md
pdm.lock
pyproject.toml
src/mkdocs_newsletter/model.py
src/mkdocs_newsletter/services/newsletter.py
src/mkdocs_newsletter/services/rss.py
src/mkdocs_newsletter/version.py
tests/unit/test_model.py
tests/unit/test_version.py

chore: cruft update

---

.cruft.json
.github/workflows/tests.yml
pdm.lock
pyproject.toml

ci: fix the markdown version until the issue is solved

---

.github/workflows/tests.yml

ci: restore python3.7 tests

---

.gitignore
Makefile
docs/examples/simple-example.py
mkdocs.yml
pdm.lock
src/mkdocs_newsletter/entrypoints/mkdocs_plugin.py
src/mkdocs_newsletter/services/nav.py
src/mkdocs_newsletter/services/newsletter.py
src/mkdocs_newsletter/services/rss.py
tests/unit/services/test_last_newsletters.py
tests/unit/services/test_nav.py

fix: mkdocs incompatibilities with latest version

---

pdm.lock
src/mkdocs_newsletter/entrypoints/mkdocs_plugin.py
src/mkdocs_newsletter/services/newsletter.py
tests/conftest.py
tests/e2e/test_plugin.py
tests/unit/services/test_last_newsletters.py
tests/unit/services/test_nav.py
tests/unit/services/test_semantic_changes.py

chore: update requirements

---

.github/workflows/install.yml
.github/workflows/tests.yml
docs/contributing.md
docs/install.md
pdm.lock
pyproject.toml
tests/e2e/test_plugin.py
tests/unit/test_model.py

fix: drop support for Python 3.7
fix: switch from pdm-pep517 to pdm-backend
chore: update requirements

feat: support Python 3.11

---

pdm.lock
pyproject.toml
src/mkdocs_newsletter/version.py
tests/conftest.py
tests/e2e/test_plugin.py
tests/unit/services/test_last_newsletters.py
tests/unit/services/test_semantic_changes.py
tests/unit/test_newsletter_template.py

chore: update dependencies
style: fix lint errors

tests: make rss tests less brittle

---

pdm.lock
src/mkdocs_newsletter/version.py
tests/conftest.py
tests/unit/services/test_last_newsletters.py
tests/unit/services/test_semantic_changes.py
tests/unit/test_newsletter_template.py

ci: update dependencies

---

pdm.lock
src/mkdocs_newsletter/services/rss.py

fix: remove deprecated findAll rss call

---

pdm.lock
pyproject.toml
src/mkdocs_newsletter/services/git.py
tests/e2e/test_plugin.py

fix: update dependencies
